### PR TITLE
[SG-235] feat: integrate token factory

### PR DESCRIPTION
**Pull request by spoo-bar**
Closes: #700

Bringing in the Osmosis token factory (as of [Osmosis v15.1.0](https://github.com/osmosis-labs/osmosis/releases/tag/v15.1.0)) to Stargaze.

The module additionally includes the changes by @larry0x which allows the denom creation to consume gas if denom creation fee is set to zero. Ref: https://github.com/public-awesome/stargaze/pull/803#issuecomment-1541932001 & https://github.com/osmosis-labs/osmosis/pull/4983

### CODE REVIEW

**Comment by faddat** [comment]
Hey, I will ask @larry0x if this is a good implementation.  Scary piece about the token factory is that there are so many versions.  @Reecepbcups did a pretty nice one for Juno though and I'm going to promote it.

**Comment by larry0x** [comment]
> Hey, I will ask @larry0x if this is a good implementation. Scary piece about the token factory is that there are so many versions. @Reecepbcups did a pretty nice one for Juno though and I'm going to promote it.

This PR seems to be simply copy-pasting code in the Osmosis repo over. **This is probably the better solution** over importing Confio or Juno's fork imo, because when Osmosis finally spins off their module into a separate repo you can simply delete the code copied over and import that repo instead. If using a forked version I'd be worried about incompatibilities.

A few suggestions:

1. I recently made a contribution to Osmosis [introducing a "denom creation gas consume" feature](https://github.com/osmosis-labs/osmosis/pull/4983). The rationale for using this over the "denom creation fee" is discussed [here](https://github.com/CosmWasm/token-factory/issues/11). Do you mind including this in your PR as well?

2. I think you need an upgrade handler to initialize the module's parameters. See [here](https://github.com/larry0x/osmosis/blob/e12c0680cadc348b6e9c66d0d336ff0db2b317b6/app/upgrades/v16/upgrades.go#L87) for an example.

3. This PR doesn't seem to include any wasm bindings. In this case, can you enable Stargate queries so that contracts can interact with the module? See [here](https://github.com/White-Whale-Defi-Platform/migaloo-chain/issues/132) for an example.

I'm happy to PRs on these if you prefer (i.e. I will make PRs targeting your branch)

**Comment by spoo-bar** [comment]
Thanks for the feedback on the PR @larry0x 

1. Will check out the "denom creation gas consume" feature as Stargaze is implementing globalfees with the upcoming release (v10) as well. 
2. Upgrade handler has intentionally not been implemented yet as token factory is planned for v11 (so upgrade after the next upgrade). 
3. Had missed the Stargate queries enabling. Thanks for the catch 👍🏻

**Comment by faddat** [comment]
seems we're on the same page on most of this.  

Thanks very much for your review Larry.  

to my knowledge no one knows exactly what to do about token factory.  Maybe I should open an issue on osmo and try to get juno changes upstreamed. 

I think both osmo and juno hoped to have it in wasmd as a first class citizen, and we (notional) maintain this thing:

https://github.com/notional-labs/wasmd/releases/tag/v0.40.0-tf.rc4

but tbh the more I think about it the more it feels like some sort of monstrosity. 

I like the modularity idea, however, there's just not a canonical source. @Reecepbcups tried to make one (valiant effort) github.com/cosmostokenfactory -- but then there were maintenance issues wrt juno.  

Tbh I am mildly out of ideas.

**Comment by larry0x** [comment]
> I think both osmo and juno hoped to have it in wasmd as a first class citizen

I think it doesn't necessarily need to be in wasmd, but definitely has to be a separate repo

Sunny seems to want it upstreamed to cosmos-sdk repo, which would take muuuuuch longer to happen

Please push for the spin off to happen Jacob

**Comment by faddat** [comment]
@larry0x -- spinoff happened and was cancelled, imo for good reason.  I like this idea of putting it in cosmos-sdk tbh.  A lot.  I would need to see if I can muster the troops to refactor it tho.

**Review by jhernandezb — APPROVED** [review]

**Pull request merged**
